Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ControleEstoque.Models
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "Informe o usuário")]
        [Display(Name="Usuário")]
        public string Usuario { get; set; }

        [Required(ErrorMessage = "Informe a senha")]
        [DataType(DataType.Password)]
        [Display(Name = "Senha")]
        public string Senha { get; set; }

        [Display(Name = "Lembrar me")]
        public bool LembrarMe { get; set; }
    }
}

Controllers/CadastroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleEstoque.Controllers
{
    public class CadastroController : Controller
    {
        [Authorize]
        public ActionResult GrupoProduto()
        {
            return View();
        }

        [Authorize]
        public ActionResult MarcaProduto()
        {
            return View();
        }

        [Authorize]
        public ActionResult LocalProduto()
        {
            return View();
        }

        [Authorize]
        public ActionResult UnidadeMedida()
        {
            return View();
        }

        [Authorize]
        public ActionResult Produto()
        {
            return View();
        }

        [Authorize]
        public ActionResult Pais()
        {
            return View();
        }

        [Authorize]
        public ActionResult Estado()
        {
            return View();
        }

        [Authorize]
        public ActionResult Cidade()
        {
            return View();
        }

        [Authorize]
        public ActionResult Fornecedor()
        {
            return View();
        }

        [Authorize]
        public ActionResult PerfilUsuario()
        {
            return View();
        }

        [Authorize]
        public ActionResult Usuario()
        {
            return View();
        }
    }
}

Controllers/ContaController.cs
using ControleEstoque.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ControleEstoque.Controllers
{
    public class ContaController : Controller
    {
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(LoginViewModel login,string returnUrl)
        {
            if (!ModelState.IsValid)
            {

                return View(login);
            }

            var achou = (login.Usuario == "danilo" && login.Senha == "123");

            if (achou)
            {
                FormsAuthentication.SetAuthCookie(login.Usuario, login.LembrarMe);

                if (Url.IsLocalUrl(returnUrl))
                {
                    return Redirect(returnUrl);
                }
                else
                {
                    RedirectToAction("Index", "Home");
                }
            }
            else
            {
                ModelState.AddModelError("", "Login inválido");
            }

            return View(login);
        }

    }
}

Controllers/GraficoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleEstoque.Controllers
{
    public class GraficoController : Controller
    {
        [Authorize]
        public ActionResult PerdaMes()
        {
            return View();
        }

        [Authorize]
        public ActionResult EntradaSaida()
        {
            return View();
        }

       
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleEstoque.Controllers
{
    public class HomeController : Controller
    {

        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        [Authorize]
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/OperacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleEstoque.Controllers
{
    public class OperacaoController : Controller
    {

        [Authorize]
        public ActionResult EntradaEstoque()
        {
            return View();
        }

        [Authorize]
        public ActionResult SaidaEstoque()
        {
            return View();
        }

        [Authorize]
        public ActionResult LancPerdaProduto()
        {
            return View();
        }

        [Authorize]
        public ActionResult Inventario()
        {
            return View();
        }

        
    }
}

Controllers/RelatorioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleEstoque.Controllers
{
    public class RelatorioController : Controller
    {

        [Authorize]
        public ActionResult PosicaoEstoque()
        {
            return View();
        }

        [Authorize]
        public ActionResult Ressuprimento()
        {
            return View();
        }
    }
}

Views/Cadastro/Cidade.cshtml
<h2>Cidade</h2>

Views/Cadastro/Estado.cshtml
<h2>Estado</h2>

Views/Cadastro/Fornecedor.cshtml
<h2>Fornecedor</h2>

Views/Cadastro/GrupoProduto.cshtml
<h2>GrupoProduto</h2>

Views/Cadastro/LocalProduto.cshtml
<h2>LocalProduto</h2>

Views/Cadastro/MarcaProduto.cshtml
<h2>MarcaProduto</h2>

Views/Cadastro/Pais.cshtml
<h2>Pais</h2>

Views/Cadastro/PerfilUsuario.cshtml
<h2>PerfilUsuario</h2>

Views/Cadastro/Produto.cshtml
<h2>Produto</h2>

Views/Cadastro/UnidadeMedida.cshtml
<h2>UnidadeMedida</h2>

Views/Cadastro/Usuario.cshtml
<h2>Usuario</h2>

Views/Conta/Login.cshtml
@model ControleEstoque.Models.LoginViewModel
@{ ViewBag.Title = "Login"; }

<div class="container">
    <div class="row">
        <h3 class="titulo">Entrar no Sistema</h3>
    </div>
    <div class="row">
        <section  id="loginForm">
            @using (Html.BeginForm("Login", "Conta", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new
            {
                @class = "form-horizontal",
                role = "form"
            }))
            {
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.Usuario, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Usuario, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Usuario, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Senha, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.Senha, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Senha, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @Html.CheckBoxFor(m => m.LembrarMe)
                        @Html.LabelFor(m => m.LembrarMe)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" class="btn btn-success" value="Entrar" />
                    </div>
                </div>}
        </section>
    </div>
</div>

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Grafico/EntradaSaida.cshtml
<h2>EntradaSaida</h2>

Views/Grafico/PerdaMes.cshtml
<h2>PerdaMes</h2>

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Operacao/EntradaEstoque.cshtml
<h2>EntradaEstoque</h2>

Views/Operacao/Inventario.cshtml
<h2>Inventario</h2>

Views/Operacao/LancPerdaProduto.cshtml
<h2>LancPerdaProduto</h2>

Views/Operacao/SaidaEstoque.cshtml
<h2>SaidaEstoque</h2>

Views/Relatorio/PosicaoEstoque.cshtml
<h2>PosicaoEstoque</h2>

Views/Relatorio/Ressuprimento.cshtml
<h2>Ressuprimento</h2>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Controle de Estoque</title>
    <link href="~/Content/css/LayoutPageAll.css" rel="stylesheet">
    <link rel="icon" href="~/Content/Img/HeadIcon.jpg" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Controle de Estoque", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Cadastros
                            <span class="caret"> </span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Grupos de produtos", "GrupoProduto", "Cadastro")</li>
                            <li>@Html.ActionLink("Marcas de produtos", "MarcaProduto", "Cadastro")</li>
                            <li>@Html.ActionLink("Locais de armazenamento", "LocalProduto", "Cadastro")</li>
                            <li>@Html.ActionLink("Produtos", "UnidadeMedida", "Cadastro")</li>
                            <li class="nav-divider"></li>
                            <li>@Html.ActionLink("Países", "Pais", "Cadastro")</li>
                            <li>@Html.ActionLink("Estados", "Estado", "Cadastro")</li>
                            <li>@Html.ActionLink("Cidades", "Cidade", "Cadastro")</li>
                            <li>@Html.ActionLink("Fornecedores", "Fornecedor", "Cadastro")</li>
                            <li class="nav-divider"></li>
                            <li>@Html.ActionLink("Perfis de Usuários", "PerfilUsuario", "Cadastro")</li>
                            <li>@Html.ActionLink("Usuários", "Usuario", "Cadastro")</li>
                        </ul>

                    </li>
                    <li>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Operações
                            <span class="caret"> </span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Entrada de produtos", "EntradaEstoque", "Operacao")</li>
                            <li>@Html.ActionLink("Saída de produtos", "SaidaEstoque", "Operacao")</li>
                            <li>@Html.ActionLink("Lançamento de perdas", "LancPerdaProduto", "Operacao")</li>
                            <li>@Html.ActionLink("Inventário de estoque", "SaidaEstoque", "Operacao")</li>
                        </ul>
                    </li>
                    <li>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Relatórios
                            <span class="caret"> </span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Posição do Estoque", "PosicaoEstoque", "Relatorio")</li>
                            <li>@Html.ActionLink("Ressuprimento", "Ressuprimento", "Relatorio")</li>
                        </ul>
                    </li>
                    <li>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Gráficos
                            <span class="caret"> </span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Perdas por mês", "PerdaMes", "Grafico")</li>
                            <li>@Html.ActionLink("Entradas vs saídas", "EntradaSaida", "Grafico")</li>
                        </ul>
                    </li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Controle de Estoque</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>

</html>